// sold flats B6 B14 A8 B11 A5 B7 B23 A21 B22 B19 B15 B18

export const data = {
    appA1: {
        apartmentImgUrl: '/apartments/A1.webp',
        floor: '1',
        beds: '2',
        direction: 'Изток',
        size: '78,73',
        sizeFull: '95,80',
        title: 'A1',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс , баня с тоалетна, мокро помещение, антре, коридор, двор.',
        textTwo: 'Към апартамента има двор с настилка 10,47кв.м. и озеленен двор 56,92кв.м. Изложението на жилището е на изток.',
        floorPlan: '/plans/first-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A1',
        appCss: 'app-A1',
        price_no_vat: '€ 187 500', 
    },
    appA2: {
        apartmentImgUrl: '/apartments/A2.webp',
        floor: '1 и 2',
        beds: '2',
        direction: 'Изток',
        size: '113,51',
        sizeFull: '138,12',
        title: 'A2',
        textOne: 'Жилището е на две нива и разполага с: първо ниво - антре, вътрешна стълба, склад, баня с тоалетна, коридор, мокро помещение, кабинет, дневна с трапезария и кухненски бокс; второ ниво – вътрешна стълба, коридор, две спални, баня с тоалетна.',
        textTwo: 'Към жилището е предвиден двор с настилка 21,77кв.м. и озеленен двор 26,25кв.м. Изложението на жилището е на изток.',
        floorPlan: '/plans/first-floor.webp',
        apartmentW: '3500',
        apartmentH: '2000',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A2',
        appCss: 'app-A2',
        price_no_vat: '€ 245 833,3333',  
    },
    appB3: {
        apartmentImgUrl: '/apartments/B3.webp',
        floor: '1 и 2',
        beds: '2',
        direction: 'Изток',
        size: '113,51',
        sizeFull: '138,12',
        title: 'B3',
        textOne: 'Жилището е на две нива и разполага с: първо ниво - антре, вътрешна стълба, склад, баня с тоалетна, коридор, мокро помещение, кабинет, дневна с трапезария и кухненски бокс; второ ниво – вътрешна стълба, коридор, две спални, баня с тоалетна.',
        textTwo: 'Към жилището е предвиден двор с настилка 21,77кв.м. и озеленен двор 26,25кв.м. Изложението на жилището е на изток.',
        floorPlan: '/plans/first-floor.webp',
        apartmentW: '3200',
        apartmentH: '1800',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'B3',
        appCss: 'app-B3',
        price_no_vat: '€ 245 833,3333',  
    },
    appA4: {
        apartmentImgUrl: '/apartments/A4.webp',
        floor: '2',
        beds: '2',
        direction: 'Изток, Запад, Юг',
        size: '78,72',
        sizeFull: '95,79',
        title: 'A4',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, килер/мокро помещение и антре.',
        textTwo: 'Изложението на жилището е на изток,запад, юг.',
        floorPlan: '/plans/second-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'A4',
        appCss: 'app-A4',
        price_no_vat: '€ 135 702,5',   
    },
    appA5: {
        apartmentImgUrl: '/apartments/A5.webp',
        floor: '2',
        beds: '0',
        direction: 'Изток, Югоизток',
        size: '38,12',
        sizeFull: '46,38',
        title: 'A5',
        textOne: 'Жилището разполага с дневна с трапезария и кухненски бокс, баня с тоалетна.',
        textTwo: 'Изложението на жилището е на изток, югозапад.',
        floorPlan: '/plans/second-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'A5',
        appCss: 'app-A5' 
    },
    appB6: {
        apartmentImgUrl: '/apartments/B6.webp',
        floor: '2',
        beds: '0',
        direction: 'Изток, Югоизток',
        size: '38,12',
        sizeFull: '46,38',
        title: 'B6',
        textOne: 'Жилището разполага с дневна с трапезария и кухненски бокс, баня с тоалетна.',
        textTwo: 'Изложението на жилището е на изток, югозапад.',
        floorPlan: '/plans/second-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B6',
        appCss: 'app-B6' 
    },
    appB7: {
        apartmentImgUrl: '/apartments/B7.webp',
        floor: '2',
        beds: '1',
        direction: 'Изток, Запад, Юг',
        size: '49,21',
        sizeFull: '59,88',
        title: 'B7',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, баня с тоалетна, мокро помещение и антре.',
        textTwo: 'Изложението на жилището е на изток, запад и юг.',
        floorPlan: '/plans/second-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B7',
        appCss: 'app-B7' 
    },
    appA8: {
        apartmentImgUrl: '/apartments/A8.webp',
        floor: '3',
        beds: '2',
        direction: 'Изток, Запад',
        size: '88,21',
        sizeFull: '107,34',
        title: 'A8',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, две лоджии, баня с тоалетна, тоалетна, коридор, килер и антре. ',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/third-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'A8',
        appCss: 'app-A8' 
    },
    appA9: {
        apartmentImgUrl: '/apartments/A9.webp',
        floor: '3',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'A9',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/third-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A9',
        appCss: 'app-A9',
        price_no_vat: '€ 186 649,5833',  
    },
    appB10: {
        apartmentImgUrl: '/apartments/B10.webp',
        floor: '3',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'B10',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/third-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'B10',
        appCss: 'app-B10',
        price_no_vat: '€ 186 649,5833',   
    },
    appB11: {
        apartmentImgUrl: '/apartments/B11.webp',
        floor: '3',
        beds: '1',
        direction: 'Изток, Запад',
        size: '58,90',
        sizeFull: '71,21',
        title: 'B11',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/third-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B11',
        appCss: 'app-B11' 
    },
    appA12: {
        apartmentImgUrl: '/apartments/A12.webp',
        floor: '4',
        beds: '2',
        direction: 'Изток, Запад',
        size: '88,21',
        sizeFull: '107,34',
        title: 'A12',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, две лоджии, баня с тоалетна, тоалетна, коридор, килер и антре. ',
        textTwo: 'Изложението на жилището е на изток, запад',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A12',
        appCss: 'app-A12',
        price_no_vat: '€ 165 482,5', 
    },
    appA13: {
        apartmentImgUrl: '/apartments/A13.webp',
        floor: '4',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'A13',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A13',
        appCss: 'app-A13',
        price_no_vat: '€ 186 649,5833',   
    },
    appB14: {
        apartmentImgUrl: '/apartments/B14.webp',
        floor: '4',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'B14',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B14',
        appCss: 'app-B14' 
    },
    appB15: {
        apartmentImgUrl: '/apartments/B15.webp',
        floor: '4',
        beds: '1',
        direction: 'Изток, Запад',
        size: '58,86',
        sizeFull: '71,63',
        title: 'B15',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B15',
        appCss: 'app-B15' 
    },
    appA16: {
        apartmentImgUrl: '/apartments/A16.webp',
        floor: '5',
        beds: '2',
        direction: 'Изток, Запад',
        size: '88,21',
        sizeFull: '107,34',
        title: 'A16',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, две лоджии, баня с тоалетна, тоалетна, коридор, килер и антре. ',
        textTwo: 'Изложението на жилището е на изток, запад',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A16',
        appCss: 'app-A16',
        price_no_vat: '€ 165 482,5',     
    },
    appA17: {
        apartmentImgUrl: '/apartments/A17.webp',
        floor: '5',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'A17',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'A17',
        appCss: 'app-A17',
        price_no_vat: '€ 186 649,5833',     
    },
    appB18: {
        apartmentImgUrl: '/apartments/B18.webp',
        floor: '5',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'B18',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B18',
        appCss: 'app-B18',
        price_no_vat: '€ 193 712',    
    },
    appB19: {
        apartmentImgUrl: '/apartments/B19.webp',
        floor: '5',
        beds: '1',
        direction: 'Изток, Запад',
        size: '58,86',
        sizeFull: '71,63',
        title: 'B19',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B19',
        appCss: 'app-B19' 
    },
    appA20: {
        apartmentImgUrl: '/apartments/A20.webp',
        floor: '6',
        beds: '2',
        direction: 'Изток, Запад',
        size: '88,21',
        sizeFull: '107,34',
        title: 'A20',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, две лоджии, баня с тоалетна, тоалетна, коридор, килер и антре. ',
        textTwo: 'Изложението на жилището е на изток, запад',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A20',
        appCss: 'app-A20',
        price_no_vat: '€ 165 482,5',      
    },
    appA21: {
        apartmentImgUrl: '/apartments/A21.webp',
        floor: '6',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'A21',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'A21',
        appCss: 'app-A21' 
    },
    appB22: {
        apartmentImgUrl: '/apartments/B22.webp',
        floor: '6',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'B22',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B22',
        appCss: 'app-B22' 
    },
    appB23: {
        apartmentImgUrl: '/apartments/B23.webp',
        floor: '6',
        beds: '1',
        direction: 'Изток, Запад',
        size: '58,86',
        sizeFull: '71,63',
        title: 'B23',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B23',
        appCss: 'app-B23' 
    },
    appA24: {
        apartmentImgUrl: '/apartments/A24.webp',
        floor: '7',
        beds: '2',
        direction: 'Изток, Запад',
        size: '88,21',
        sizeFull: '107,34',
        title: 'A24',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, две лоджии, баня с тоалетна, тоалетна, коридор, килер и антре. ',
        textTwo: 'Изложението на жилището е на изток, запад',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A24',
        appCss: 'app-A24',
        price_no_vat: '€ 165 482,5',      
    },
    appA25: {
        apartmentImgUrl: '/apartments/A25.webp',
        floor: '7',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'A25',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'A25',
        appCss: 'app-A25' 
    },
    appB26: {
        apartmentImgUrl: '/apartments/B26.webp',
        floor: '7',
        beds: '2',
        direction: 'Изток, Запад',
        size: '99,49',
        sizeFull: '121,07',
        title: 'B26',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, лоджия, две бани с тоалетни, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'B26',
        appCss: 'app-B26',
        price_no_vat: '€ 171 515,83',   
    },
    appB27: {
        apartmentImgUrl: '/apartments/B27.webp',
        floor: '7',
        beds: '1',
        direction: 'Изток, Запад',
        size: '58,86',
        sizeFull: '71,63',
        title: 'B27',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/fourth-to-seventh-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B27',
        appCss: 'app-B27',
        price_no_vat: '€ 114 608',    
    },
    appA28: {
        apartmentImgUrl: '/apartments/A28.webp',
        floor: '8',
        beds: '2',
        direction: 'Изток, Запад',
        size: '88,21',
        sizeFull: '107,35',
        title: 'A28',
        textOne: 'Жилището разполага с две спални, дневна с трапезария и кухненски бокс, две лоджии, баня с тоалетна, тоалетна, коридор, килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/eight-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A28',
        appCss: 'app-A28',
        price_no_vat: '€ 165 497,9167',      
    },
    appA29: {
        apartmentImgUrl: '/apartments/A29.webp',
        floor: '8 и 9',
        beds: '3',
        direction: 'Изток, Запад, Юг',
        size: '143,78',
        sizeFull: '174,96',
        title: 'A29',
        textOne: 'Жилището е на две нива и разполага с: първо ниво - антре, вътрешна стълба, килер, баня с тоалетна, тоалетна, дневна с трапезария и кухненски бокс и една спалня; второ ниво – вътрешна стълба, коридор, две спални, дрешник, баня с тоалетна, лоджия.',
        textTwo: 'Изложението на жилището е на  изток, запад и юг.',
        floorPlan: '/plans/eight-floor.webp',
        apartmentW: '7500',
        apartmentH: '3300',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'A29',
        appCss: 'app-A29',
        price_no_vat: '€ 269 730',   
    },
    appB30: {
        apartmentImgUrl: '/apartments/B30.webp',
        floor: '8 и 9',
        beds: '3',
        direction: 'Изток, Запад, Юг',
        size: '143,78',
        sizeFull: '174,96',
        title: 'B30',
        textOne: 'Жилището е на две нива и разполага с: първо ниво - антре, вътрешна стъблба, килер, баня с тоалетна, тоалетна, дневна с трапезария и кухненски бокс и една спалня; второ ниво – вътрешна стълба, коридор, две спални, дрешник, баня с тоалетна, лоджия.',
        textTwo: 'В стойността на жилището са включени мазе и паркомясто в подземен гараж. Възможност за закупуване на второ паркомясто.',
        textTwo: 'Изложението на жилището е на  изток, запад и юг.',
        apartmentW: '7000',
        apartmentH: '2200',
        floorW: '9850',
        floorH: '6000',
        available: true,
        appLink: 'B30',
        appCss: 'app-B30',
        price_no_vat: '€ 269 730',    
    },
    appB31: {
        apartmentImgUrl: '/apartments/B31.webp',
        floor: '8',
        beds: '1',
        direction: 'Изток, Запад',
        size: '58,90',
        sizeFull: '71,68',
        title: 'B31',
        textOne: 'Жилището разполага с една спалня, дневна с трапезария и кухненски бокс, лоджия, баня с тоалетна, мокро помещение с килер и антре.',
        textTwo: 'Изложението на жилището е на изток, запад.',
        floorPlan: '/plans/eight-floor.webp',
        apartmentW: '3200',
        apartmentH: '3200',
        floorW: '9850',
        floorH: '6000',
        available: false,
        appLink: 'B31',
        appCss: 'app-B31',
        price_no_vat: '€ 101 546,66',  
    },
}