// sold units:
// parkspaces: 3, 5
// garages: 4, 5

export const dataGarage = {
    garage1: {
        title: 'Гараж 1',
        floor: '-1',
        size: '28,06',
        price: '€ 28 000',
        extra: '',
        available: true,
    },
    garage2: {
        title: 'Гараж 2',
        floor: '-1',
        size: '26,58',
        price: '€ 30 000',
        extra: '',
        available: true,
    },
    garage3: {
        title: 'Гараж 3',
        floor: '-1',
        size: '23,41',
        price: '€ 44 000',
        extra: '✔️',
        available: true,
    },
    garage4: {
        title: 'Гараж 4',
        floor: '-1',
        size: '25,64',
        price: '€ 48 000',
        extra: '✔️',
        available: false,
    },
    garage5: {
        title: 'Гараж 5',
        floor: '-1',
        size: '27,47',
        price: '€ 48 000',
        extra: '✔️',
        available: false,
    },
    garage6: {
        title: 'Гараж 6',
        floor: '-1',
        size: '27,47',
        price: '€ 44 000',
        extra: '✔️',
        available: true,
    },
    garage7: {
        title: 'Гараж 7',
        floor: '-1',
        size: '25,64',
        price: '€ 44 000',
        extra: '✔️',
        available: true,
    },
    garage8: {
        title: 'Гараж 8',
        floor: '-1',
        size: '23,42',
        price: '€ 44 000',
        extra: '✔️',
        available: true,
    },
    garage9: {
        title: 'Гараж 9',
        floor: '-2',
        size: '28,06',
        price: '€ 26 500',
        extra: '',
        available: true,
    },
    garage10: {
        title: 'Гараж 10',
        floor: '-2',
        size: '26,77',
        price: '€ 30 000',
        extra: '',
        available: true,
    },
    garage11: {
        title: 'Гараж 11',
        floor: '-2',
        size: '23,41',
        price: '€ 26 500',
        extra: '',
        available: true,
    },
    garage12: {
        title: 'Гараж 12',
        floor: '-2',
        size: '25,64',
        price: '€ 26 500',
        extra: '',
        available: true,
    },
    garage13: {
        title: 'Гараж 13',
        floor: '-2',
        size: '27,47',
        price: '€ 29 000',
        extra: '',
        available: true,
    },
    garage14: {
        title: 'Гараж 14',
        floor: '-2',
        size: '27,47',
        price: '€ 29 000',
        extra: '',
        available: true,
    },
    garage15: {
        title: 'Гараж 15',
        floor: '-2',
        size: '25,64',
        price: '€ 26 500',
        extra: '',
        available: true,
    },
    garage16: {
        title: 'Гараж 16',
        floor: '-2',
        size: '23,42',
        price: '€ 25 000',
        extra: '',
        available: true,
    },
    garage17: {
        title: 'Гараж 17',
        floor: '0',
        size: '20,51',
        price: '€ 30 000',
        extra: '',
        available: true,
    },
    parkspace1: {
        title: 'Паркомясто 1',
        floor: '0',
        size: '12,50',
        price: '€ 20 000',
        extra: '',
        available: true,
    },
    parkspace2: {
        title: 'Паркомясто 2',
        floor: '0',
        size: '12,50',
        price: '€ 20 000',
        extra: '',
        available: true,
    },
    parkspace3: {
        title: 'Паркомясто 3',
        floor: '0',
        size: '15,66',
        price: '€ 20 000',
        extra: '',
        available: false,
    },
    parkspace4: {
        title: 'Паркомясто 4',
        floor: '0',
        size: '18,00',
        price: '€ 20 000',
        extra: '',
        available: true,
    },
    parkspace5: {
        title: 'Паркомясто 5',
        floor: '-1',
        size: '13,69',
        price: '€ 20 000',
        extra: '',
        available: false,
    },
    parkspace6: {
        title: 'Паркомясто 6',
        floor: '-1',
        size: '15,13',
        price: '€ 33 000',
        extra: '✔️',
        available: true,
    },
    parkspace7: {
        title: 'Паркомясто 7',
        floor: '-1',
        size: '15,14',
        price: '€ 33 000',
        extra: '✔️',
        available: true,
    },
    parkspace8: {
        title: 'Паркомясто 8',
        floor: '-2',
        size: '13,48',
        price: '€ 20 000',
        extra: '',
        available: true,
    },
    parkspace9: {
        title: 'Паркомясто 9',
        floor: '-2',
        size: '18,00',
        price: '€ 22 000',
        extra: '',
        available: true,
    },
    parkspace10: {
        title: 'Паркомясто 10',
        floor: '-2',
        size: '12,50',
        price: '€ 19 000',
        extra: '',
        available: true,
    },
}